### ISSUE TITLE
maxVolume is being calculated as an absolute value over all time

### ISSUE THREAD

**Issue by garadox** [OskarKjellin/vizceral-hystrix#3]
Looking at the examples for the vizceral dashboard, maxVolume is commented as "// The maximum volume seen recently to relatively measure particle density".

Unfortunately, relatively is not defined, but currently if a large volume of traffic is seen, and then is reduced, maxVolume never lowers and the vizceral dashboard ends up with extremely low particle density.

I've only got one idea to better calculate maxVolume as a relative number:
- Change a cluster to store maxVolume as a list, with the maxVolume value and a timestamp of when it was recorded
- Each time a new maxVolume is seen, record the new value and the current timestamp
- When a request is made for the vizceral-aggregated data, find maxVolume from the list, but disregard / anything older than x time (where x time is 10 seconds, matching the default hystrix sample size)
- When a new maxVolume is added, ideally clean up timestamps that are below the threshold of x above.

I'll try to get some time this week to post a suggested PR, but i'll admit that rxJava still isn't my strongest work :)

**Comment by OskarKjellin** [comment]
Sorry for the late reply once again :) Working on a solution this weekend. I think I'll find a nice way in rx to solve it

**Comment by OskarKjellin** [comment]
Please try the fix and see if it works for you @garadox

**Comment by garadox** [comment]
Thanks for the update - I like the elegance of the solution :)

Will get it rolled out and let you know how it goes in the next few days.

**Comment by OskarKjellin** [comment]
Thanks, rx solutions usually become very elegant once you find the right api. Took me a while :)

Let me know how it goes!

**Comment by garadox** [comment]
Sorry I've not got this tested yet - working on it this week and will give you feedback if there are nay issues.

**Comment by garadox** [comment]
Have been running the update in production for the last week - looking good!

**Comment by OskarKjellin** [comment]
Glad to hear!
