### ISSUE TITLE
Multiple regions?

### ISSUE THREAD

**Issue by zdlgrj** [OskarKjellin/vizceral-hystrix#4]
Hi,

Does vizceral-hystrix already support multiple regions through config.json?

**Comment by OskarKjellin** [comment]
Yeah you can simply specify multiple config.json, check the readme there is a sample there:
`java -jar vizceral-hystrix-1.0.0.jar eu-west-1.json eu-west-2.json`

**Comment by zdlgrj** [comment]
Oh, yeah, i missed that, thanks!

**Comment by OskarKjellin** [comment]
No worries :)
