### ISSUE TITLE
Not getting json with normal, danger and maxVolume counts

### ISSUE THREAD

**Issue by sathesherode** [OskarKjellin/vizceral-hystrix#5]

**Comment by OskarKjellin** [comment]
In the original ticket you linked a couple of projects. I looked at them and couldn't find any usages of the hystrix stream servlet being in there? Have you also setup turbine locally?

https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-metrics-event-stream

**Comment by sathesherode** [comment]
I used spring cloud annotations to enable the hystrix stream and I am getting the below stream.

[{  
   "type":"HystrixCommand",
   "name":"MyHystrixCommand",
   "group":"MyHystrix",
   "currentTime":1500900005412,
   "isCircuitBreakerOpen":false,
   "errorPercentage":0,
   "errorCount":0,
   "requestCount":1,
   "rollingCountBadRequests":0,
   "rollingCountCollapsedRequests":0,
   "rollingCountEmit":0,
   "rollingCountExceptionsThrown":0,
   "rollingCountFailure":0,
   "rollingCountFallbackEmit":0,
   "rollingCountFallbackFailure":0,
   "rollingCountFallbackMissing":0,
   "rollingCountFallbackRejection":0,
   "rollingCountFallbackSuccess":0,
   "rollingCountResponsesFromCache":0,
   "rollingCountSemaphoreRejected":0,
   "rollingCountShortCircuited":0,
   "rollingCountSuccess":1,
   "rollingCountThreadPoolRejected":0,
   "rollingCountTimeout":0,
   "currentConcurrentExecutionCount":0,
   "rollingMaxConcurrentExecutionCount":1,
   "latencyExecute_mean":17,
   "latencyExecute":{  
      "0":17,
      "25":17,
      "50":17,
      "75":18,
      "90":18,
      "95":18,
      "99":18,
      "99.5":18,
      "100":18
   },
   "latencyTotal_mean":18,
   "latencyTotal":{  
      "0":17,
      "25":17,
      "50":17,
      "75":19,
      "90":19,
      "95":19,
      "99":19,
      "99.5":19,
      "100":19
   },
   "propertyValue_circuitBreakerRequestVolumeThreshold":3,
   "propertyValue_circuitBreakerSleepWindowInMilliseconds":30000,
   "propertyValue_circuitBreakerErrorThresholdPercentage":50,
   "propertyValue_circuitBreakerForceOpen":false,
   "propertyValue_circuitBreakerForceClosed":false,
   "propertyValue_circuitBreakerEnabled":true,
   "propertyValue_executionIsolationStrategy":"THREAD",
   "propertyValue_executionIsolationThreadTimeoutInMilliseconds":1000,
   "propertyValue_executionTimeoutInMilliseconds":1000,
   "propertyValue_executionIsolationThreadInterruptOnTimeout":true,
   "propertyValue_executionIsolationThreadPoolKeyOverride":null,
   "propertyValue_executionIsolationSemaphoreMaxConcurrentRequests":10,
   "propertyValue_fallbackIsolationSemaphoreMaxConcurrentRequests":10,
   "propertyValue_metricsRollingStatisticalWindowInMilliseconds":10000,
   "propertyValue_requestCacheEnabled":true,
   "propertyValue_requestLogEnabled":true,
   "reportingHosts":1,
   "threadPool":"MyHystrix"
}]

Yes I have done the turbine setup locally.

**Comment by OskarKjellin** [comment]
Long time since I touched the code, but it seems like you have 0.1 req/s. With integer rounding to an integer that will be 0 req/s. Can you verify that it works if you add some traffic?
https://github.com/OskarKjellin/vizceral-hystrix/blob/master/src/main/java/vizceral/hystrix/HystrixReader.java#L109

**Comment by sathesherode** [comment]
Yes I will check it. Meanwhile what is 'INTERNET' region? Because I am expecting to use my client microservice(HYSTRIX-LS) as 'INTERNET' but I am getting it as a node inside the 'INTERNET' region.

**Comment by OskarKjellin** [comment]
INTERNET is traffic coming into your service from outside. It's defined in the vizceral spec. You'll see it here for instance https://github.com/Netflix/Vizceral/wiki/How-to-Use#graph-data-format

**Comment by sathesherode** [comment]
Yes in this case I am trying to use my client microservice (HystrixLS) as 'INTERNET' because HystrixLS is sending traffic to the actual microservices (HystrixService and HystrixBackupService). Is it possible?

**Comment by OskarKjellin** [comment]
Yeah that should be fine. You still need an INTERNET node tho, otherwise vizceral gets sad

Is HystrixLS generating it's own traffic without taking it from end users?

**Comment by sathesherode** [comment]
Yes HystrixLS is receiving traffic from the end users. Also I am getting **normal** and **danger** count now after sending more traffic.

HystrixLS is getting data from HystrixService. Both are different microservices which runs in a same region but on different ports. In the config.json I am able to specify only 1 port. So how can I get json of both services in a same region? In other words how to specify more than one port in order to get stream from multiple services running in the same region?

**Comment by OskarKjellin** [comment]
Ok, so you should put HystrixLS as an "internet cluster".

The tool expects to tail a turbine stream. One turbine server runs on one port and aggregates multiple services that can run on multiple ports (IIRC). But for that you'll have to consult the turbine documentation.
